server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/spring_hiber
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    open-in-view: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true